global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'openaccess-mcp'
    environment: 'production'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # OpenAccess MCP Server
  - job_name: 'openaccess-mcp'
    static_configs:
      - targets: ['openaccess-mcp:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    
    # Relabeling for better metric names
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: port
        regex: '([^:]+):(\d+)'
        replacement: '${2}'
      - source_labels: [__address__]
        target_label: host
        regex: '([^:]+):\d+'
        replacement: '${1}'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for common queries
rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml"
